version: "3.4"

services:
  publisher:
    command: sh -c /app/entry.sh
    image: securityunion/rust-dev:latest
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./publisher
        target: /app
    networks:
      - backend
    depends_on:
      - rabbit


  consumer_securityunion:
    command: sh -c /app/entry.sh
    image: securityunion/rust-dev:latest
    environment:
      QUEUE_ID: securityunion
    volumes:
      - type: bind
        source: ./consumer
        target: /app
    networks:
      - backend
    depends_on:
      - rabbit

  rabbit:
    image: "rabbitmq:latest"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "5672:5672"
    networks:
      - backend

networks:
    backend:
        driver: bridge
