version: "3.4"
services:
  publisher:
    command: cargo watch -x run
    build:
        context: ./publisher
        cache_from:
          - securityunion/rust-dev:latest
    ports:
      - "8000:8000"

  consumer_securityunion:
    command: cargo watch -x run
    build:
      context: ./consumer
      cache_from:
        - securityunion/rust-dev:latest
    environment: 
      QUEUE_ID: "securityunion"

  rabbit:
    image: "rabbitmq:latest"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "5672:5672"
